volumes:
  my_stack_local_postgres_data: {}
  my_stack_local_postgres_data_backups: {}
  
services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: my_stack_production_postgres
    container_name: my_stack_local_postgres
    volumes:
      - my_stack_local_postgres_data:/var/lib/postgresql/18/docker
      - my_stack_local_postgres_data_backups:/backups
    ports:
      - "8832:5432"
    env_file:
      - ./.envs/.local/.postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./choppi-backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./.envs/.local/.backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./choppi-backend:/app
      - /app/node_modules

  frontend:
    env_file:
      - ./.envs/.local/.frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run start
