volumes:
  my_stack_production_postgres_data: {}
  my_stack_production_postgres_data_backups: {}

services:
  postgres:
    image: myapp_postgres
    container_name: myapp_postgres
    volumes:
      - my_stack_production_postgres_data:/var/lib/postgresql/18/docker
      - my_stack_production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_stack_network
    ports:
      - "8832:5432"

  backend:
    image: myapp_backend
    container_name: myapp_backend
    env_file:
      - ./.envs/.production/.backend
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my_stack_network

  nginx_frontend:
    image: myapp_nginx_frontend
    container_name: myapp_nginx_frontend
    env_file:
      - ./.envs/.production/.frontend
    networks:
      - my_stack_network

  nginx_backend:
    image: myapp_nginx_backend
    container_name: myapp_nginx_backend
    depends_on:
      - backend
    networks:
      - my_stack_network

  traefik:
    image: myapp_traefik
    container_name: myapp_traefik
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    ports:
      - "80:80"
      - "8000:8000"
    networks:
      - my_stack_network

networks:
  my_stack_network:
    driver: bridge