log:
  level: INFO

entryPoints:
  web:
    address: ':80'

  web-backend:
    address: ':8000'

http:
  routers:
    frontend-router:
      # rule: "PathPrefix(`/home`)" 
      rule: "Host(`172.31.75.75`)"
      entryPoints:
        - web
      service: nginx-frontend

    backend-router:
      rule: "Host(`172.31.75.75`) || PathPrefix(`/api`)"
      entryPoints:
        - web-backend
      service: nginx-backend

  services:
    nginx-frontend:
      loadBalancer:
        servers:
          - url: http://nginx_frontend:80

    nginx-backend:
      loadBalancer:
        servers:
          - url: http://nginx_backend:80

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
