log:
  level: INFO

entryPoints:
  web:
    address: ':80'

http:
  routers:
    frontend-router:
      rule: "PathPrefix(`/app`)"
      entryPoints:
        - web
      service: nginx-frontend

    backend-router:
      rule: "PathPrefix(`/api`)"
      entryPoints:
        - web
      service: nginx-backend

  services:
    nginx-frontend:
      loadBalancer:
        servers:
          - url: http://nginx_frontend:80

    nginx-backend:
      loadBalancer:
        servers:
          - url: http://nginx_backend:80

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
